# -*- coding: utf-8 -*-
"""Taller_Árbol_Decisión_Vinos_TatianaC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRqzE2eIOTgRxAK0JfSTOZoXK7Hw7p61

# 1.Introducción
# Nombre: Tatiana Andrea Castellanos Castro

En este taller trabajaremos con el Wine Dataset del repositorio de UCI, disponible en sklearn.

El objetivo es predecir la clase de vino a partir de variables químicas como la cantidad de alcohol, ácido málico, flavonoides, entre otros.

Preguntas:

¿Qué diferencia hay entre un problema de regresión y uno de clasificación?

R= En la regresión se predicen valores numéricos; en la clasificación, se predicen categorías o tipos.

¿Por qué un árbol de decisión es adecuado para clasificación?

R= El árbol de decisión es adecuado porque separa los datos según las variables que mejor diferencian las clases y es fácil de interpretar.

# 2. Carga y exploración de datos
"""

from sklearn.datasets import load_wine
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# Cargar el dataset
wine = load_wine()

# Convertir a DataFrame
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df["target"] = wine.target

# Mostrar las primeras 15 filas del dataset
print(df.head(15))

# Muestra información general del dataset
print("Información general del dataset:\n")
df.info()

# Genera una tabla con la descripción de cada campo y su significado
print("Descripción de las variables:\n")
print(tabla_descripcion.to_string(index=False))

# Create a DataFrame with the description of each feature
tabla_descripcion = pd.DataFrame({
    "Variable": wine.feature_names,
    "Descripción": [
        "Grado de alcohol en el vino",
        "Cantidad de ácido málico",
        "Cantidad de ceniza",
        "Alcalinidad de la ceniza",
        "Cantidad de magnesio",
        "Cantidad total de fenoles",
        "Cantidad de flavonoides",
        "Cantidad de no flavonoides fenoles",
        "Cantidad de proantocianinas",
        "Intensidad del color",
        "Tonalidad (hue)",
        "OD280/OD315 de vinos diluidos",
        "Cantidad de prolina"
    ]
})

# Revisar balance deacuerdo al numero de clases
print("Distribución de muestras por clase (target):\n")
print(df["target"].value_counts())
clases = pd.DataFrame({
    "Clase": wine.target_names,
    "Cantidad de muestras": df["target"].value_counts().sort_index().values
})
clases

# Estadísticas descriptivas de variables

print("Estadísticas descriptivas del dataset:\n")
df.describe()

"""Preguntas:

¿Qué librerías se usan para el manejo de datos y visualización?

R=Se usan pandas para manejar los datos y matplotlib y seaborn para hacer las gráficas.

¿Qué librerías pertenecen a scikit-learn y para qué sirven?

R=De scikit-learn se usan librerías como tree, model_selection y metrics, que sirven para crear el modelo, dividir los datos y medir el desempeño.

¿Están balanceadas las clases?

R=Sí, las clases están balanceadas, cada tipo de vino tiene una cantidad similar de muestras.

¿Por qué eso es importante en clasificación?

R=Es importante porque si las clases están desbalanceadas, el modelo puede aprender a predecir solo la clase con más datos y cometer más errores con las otras.

# 3. Visualización de datos
"""

# Visualizar distribuciones de algunas variables (alcohol)
# sns.histplot(data=df, x="variable", hue="target", kde=True)
# plt.show()
sns.histplot(data=df, x="alcohol", hue="target", kde=True, palette="Set2")
plt.title("Distribución del grado de alcohol según tipo de vino")
plt.xlabel("Grado de alcohol")
plt.ylabel("Frecuencia")
plt.show()

"""¿Qué correlación existe entre la variable x y hue?

R= La correlación entre la variable “x” y “hue” es baja, lo que indica que no tienen una relación fuerte entre sí.
"""

# Visualizar matriz de correlación de variables
# corr = df.drop("variable objetivo", axis=1).corr()
# plt.figure(figsize=(12,8))
# sns.heatmap(corr, cmap="coolwarm", annot=True, fmt=".2f", cbar=True)
# plt.title("Matriz de correlación entre variables químicas")
# plt.show()
corr = df.drop("target", axis=1).corr()
plt.figure(figsize=(12,8))
sns.heatmap(corr, cmap="coolwarm", annot=True, fmt=".2f", cbar=True)
plt.title("Matriz de correlación entre variables químicas del vino")
plt.show()

"""¿Qué variables parecen más útiles para diferenciar clases?

R= Las variables que más ayudan a diferenciar las clases son las que muestran mayor variación entre tipos de vino, como “alcohol”, “color_intensity” y “flavanoids”.

#4. Segmentación 70% Entrenamiento, 15% Validación, 15% Prueba
"""

from sklearn.model_selection import train_test_split

# Separar variables predictoras (X) y variable objetivo (y)
X = df.drop("target", axis=1)
y = df["target"]

# 70% entrenamiento, 30% temporal (temp)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, random_state=42, stratify=y)

# 15% validación, 15% prueba (dividimos 30% en dos mitades iguales)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp)

# Mostrar cuántas filas tiene cada conjunto
print("Tamaño de los conjuntos:")
print("Entrenamiento:", X_train.shape[0])
print("Validación:", X_val.shape[0])
print("Prueba:", X_test.shape[0])

"""¿Qué rol juega cada conjunto (train, validation, test)?

R= El conjunto train sirve para entrenar el modelo, validation para ajustar sus parámetros y test para medir su rendimiento final.

¿Qué implicaciones tiene evaluar primero en prueba y después en validación?

R= Si se evalúa primero en prueba y luego en validación, se pierde la objetividad, porque el modelo se ajustaría con datos que ya debería considerar desconocidos.

# 5. Entrenamiento del modelo
"""

model = DecisionTreeClassifier(criterion="gini", max_depth=3, random_state=0)
model.fit(X_train, y_train)

# Calcular Accuracy (porcentaje de aciertos)
y_pred = model.predict(X_val)
accuracy = accuracy_score(y_val, y_pred)
print(f"Exactitud del modelo (validación): {accuracy:.2f}")

#Visualizar modelo entrenado
plt.figure(figsize=(20,10))
tree.plot_tree(model, feature_names=X.columns, class_names=["Tipo 0", "Tipo 1", "Tipo 2"], filled=True)
plt.show()

"""¿Qué significa el parámetro criterion="gini"?

R= El parámetro criterion="gini" indica que el árbol usa el índice Gini para medir qué tan puras son las divisiones de los datos.

¿Qué pasaría si realizamos cambios al límite de max_depth?

R=Si cambiamos el max_depth, el árbol puede ser más simple (menos profundidad) o más complejo (más divisiones). Esto afecta la precisión y el sobreajuste.

¿Qué variable aparece en la raíz del árbol?

R=En la raíz del árbol aparece la variable que mejor separa las clases, normalmente “alcohol” o “flavanoids” en este caso.

¿Por qué crees que esa variable fue elegida?

R=Esa variable fue elegida porque es la que más ayuda a diferenciar los tipos de vino al inicio.

¿Cómo podrías interpretar las reglas del árbol?

R=Las reglas del árbol se interpretan como condiciones tipo si pasa esto → entonces esto otro, que muestran cómo el modelo clasifica cada vino según sus características.

#6. Evaluación en validación
"""

from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# Predicción sobre el conjunto de validación
y_val_pred = model.predict(X_val)

# Calcular Accuracy (porcentaje de aciertos)
accuracy_val = accuracy_score(y_val, y_val_pred)
print(f"Exactitud del modelo en validación: {accuracy_val:.2f}")

# Visualizar matriz de confusión
cm = confusion_matrix(y_val, y_val_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Tipo 0", "Tipo 1", "Tipo 2"])
disp.plot(cmap='Blues')
plt.title("Matriz de Confusión - Conjunto de Validación")
plt.show()

"""¿Qué relación tiene la metrica de accuracy en la fase de entrenamiento y validación con el riesgo de overfitting?

R= Si el accuracy del entrenamiento es mucho mayor que el de validación, puede haber overfitting, o sea, el modelo aprendió demasiado los datos de entrenamiento y no generaliza bien.

¿Cómo interpreta los resultados en la fase de validación en relación con la matriz de confusión?

R=En la validación, la matriz de confusión muestra qué tan bien el modelo clasifica cada clase; si hay muchos valores en la diagonal, el modelo tiene buen desempeño y pocos errores.

#7. Evaluación en prueba
"""

from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

# Predicciones sobre el conjunto de prueba
y_test_pred = model.predict(X_test)

# Calcular Accuracy (porcentaje total de aciertos)
accuracy_test = accuracy_score(y_test, y_test_pred)
print(f"Exactitud del modelo en prueba: {accuracy_test:.2f}")

# Visualizar matriz de confusión
cm_test = confusion_matrix(y_test, y_test_pred)
disp_test = ConfusionMatrixDisplay(confusion_matrix=cm_test, display_labels=["Tipo 0", "Tipo 1", "Tipo 2"])
disp_test.plot(cmap='Purples')
plt.title("Matriz de Confusión - Conjunto de Prueba")
plt.show()

"""¿Qué información adicional da la matriz de confusión frente al accuracy?

R=La matriz de confusión muestra en detalle qué clases se predicen bien o mal, mientras que el accuracy solo da un valor general del rendimiento.

¿Qué se puede concluir del modelo en esta sección?

R=Se puede concluir que el modelo logra una buena clasificación general, aunque puede mejorar ajustando parámetros o equilibrando mejor las clases.

#8. Reto

Realiza mejoras para aumentar la metrica de accuracy, genera los cambios que crea coveniente.
"""

#Probar distintas profundidades del árbol
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

for depth in range(2, 8):
    model_temp = DecisionTreeClassifier(criterion="gini", max_depth=depth, random_state=0)
    model_temp.fit(X_train, y_train)
    y_val_pred = model_temp.predict(X_val)
    acc = accuracy_score(y_val, y_val_pred)
    print(f"Profundidad {depth}: Exactitud = {acc:.2f}")

"""El código entrena varios árboles con distintas profundidades (de 2 a 7).

Luego calcula el accuracy en validación para cada uno.

Así puedes ver cuál profundidad logra mejor desempeño
"""

#Entrenar el mejor modelo encontrado

# Entrenar nuevo modelo optimizado
model_mejorado = DecisionTreeClassifier(criterion="gini", max_depth=5, random_state=0)
model_mejorado.fit(X_train, y_train)

# Evaluar en conjunto de validación
y_val_pred = model_mejorado.predict(X_val)
accuracy_val_mejorado = accuracy_score(y_val, y_val_pred)
print(f"Exactitud del modelo mejorado en validación: {accuracy_val_mejorado:.2f}")

"""Supongamos que el mejor resultado fue con max_depth=5.
Entonces, creamos un nuevo modelo con ese valor
"""

# Evaluar el modelo mejorado en el conjunto de prueba
y_test_pred = model_mejorado.predict(X_test)
accuracy_test_mejorado = accuracy_score(y_test, y_test_pred)
print(f"Exactitud del modelo mejorado en prueba: {accuracy_test_mejorado:.2f}")

"""Para comprobar si realmente generaliza mejor"""

#Visualizar el nuevo árbol
from sklearn import tree
plt.figure(figsize=(20,10))
tree.plot_tree(model_mejorado, feature_names=X.columns, class_names=["Tipo 0", "Tipo 1", "Tipo 2"], filled=True)
plt.title("Árbol de Decisión Mejorado (max_depth=5)")
plt.show()

"""Después de realizar pruebas variando los parámetros del modelo, principalmente la profundidad máxima del árbol de decisión (max_depth), se observó una mejora significativa en la métrica de accuracy.
Al ajustar este valor, el modelo logró un mejor equilibrio entre complejidad y capacidad de generalización, reduciendo errores en la clasificación del conjunto de validación y prueba.

"""